/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Raydo
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGeneral
     */
    public VentanaMenu() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Adivinar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        InicializarBC = new javax.swing.JButton();
        GraficarBC = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(88, 204, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Niagara Engraved", 0, 90)); // NOI18N
        jLabel3.setText("AKINATOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 210, 70));

        Salir.setBackground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 250, -1));

        Adivinar.setBackground(new java.awt.Color(255, 255, 255));
        Adivinar.setText("Adivinar");
        Adivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdivinarActionPerformed(evt);
            }
        });
        jPanel1.add(Adivinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 250, -1));

        Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Buscar existencia de un animal");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 250, -1));

        InicializarBC.setBackground(new java.awt.Color(255, 255, 255));
        InicializarBC.setText("Inicializar base de conocimientos");
        jPanel1.add(InicializarBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 250, -1));

        GraficarBC.setBackground(new java.awt.Color(255, 255, 255));
        GraficarBC.setText("Graficar base de conocimientos");
        GraficarBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficarBCActionPerformed(evt);
            }
        });
        jPanel1.add(GraficarBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 250, -1));

        Regresar.setBackground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Reelegir la base de conocimientos");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/akinator1.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 270, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void AdivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdivinarActionPerformed
        new VentanaAdivinar().setVisible(true);
        dispose();
    }//GEN-LAST:event_AdivinarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        new VentanaBuscarAnimal().setVisible(true);
        dispose();
    }//GEN-LAST:event_BuscarActionPerformed

    private void GraficarBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficarBCActionPerformed
        new VentanaGraficar().setVisible(true);
        dispose();
    }//GEN-LAST:event_GraficarBCActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        new VentanaEscogerCsv().setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adivinar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton GraficarBC;
    private javax.swing.JButton InicializarBC;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
